"""second upgrade

Revision ID: cacc782ae4f5
Revises: 3f5a2cee36b9
Create Date: 2024-06-20 14:05:29.893811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cacc782ae4f5'
down_revision = '3f5a2cee36b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['property.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['property.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('details', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('price', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.String(length=10), nullable=False))
        batch_op.drop_constraint('booking_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('booking_ibfk_1', type_='foreignkey')
        batch_op.drop_column('check_in')
        batch_op.drop_column('check_out')
        batch_op.drop_column('created_at')
        batch_op.drop_column('property_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=True))

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('sold')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('property_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('check_out', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('check_in', mysql.DATETIME(), nullable=False))
        batch_op.create_foreign_key('booking_ibfk_1', 'property', ['property_id'], ['id'])
        batch_op.create_foreign_key('booking_ibfk_2', 'user', ['user_id'], ['id'])
        batch_op.drop_column('rating')
        batch_op.drop_column('price')
        batch_op.drop_column('details')
        batch_op.drop_column('name')
        batch_op.drop_column('image')

    op.drop_table('transaction')
    op.drop_table('my_bookings')
    # ### end Alembic commands ###
